# tests/system/test_scp_complete_system.py
"""System-level test suite for SCP complete audit.

This test runs the strict system audit script (`scripts/run_system_audit_strict.py`)
and validates that all required gates pass with no blockers.
It uses the SCP DNA principles by ensuring the evidence (report.json)
matches the expected strict gate outcomes before marking the test as passed.
"""

import json
import subprocess
import sys
import os
from pathlib import Path

import pytest

# Path to the audit script and its report output
AUDIT_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "run_system_audit_strict.py"
REPORT_PATH = Path(__file__).resolve().parents[2] / "reports" / "system_audit_strict" / "report.json"

def run_audit() -> subprocess.CompletedProcess:
    """Execute the strict audit script.

    Returns the CompletedProcess instance. The script should exit with code 0.
    """
    env = {**os.environ, "PYTHONPATH": str(Path(__file__).resolve().parents[2])}
    return subprocess.run(
        [sys.executable, str(AUDIT_SCRIPT)],
        cwd=str(AUDIT_SCRIPT.parent),
        env=env,
        capture_output=True,
        text=True,
    )

def load_report() -> dict:
    """Load the JSON report generated by the audit script."""
    assert REPORT_PATH.is_file(), f"Report not found at {REPORT_PATH}"
    with open(REPORT_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def test_strict_audit_success():
    """Run the strict audit and verify that it succeeds without blockers.

    The SCP DNA principle *Reality > Model* is respected by checking the
    actual exit code and the concrete JSON report generated by the audit.
    """
    result = run_audit()
    assert result.returncode == 0, f"Audit script failed (code {result.returncode}):\n{result.stderr}"

    report = load_report()
    required_keys = {"gates", "blockers", "summary"}
    assert required_keys.issubset(report.keys()), f"Missing keys in report: {required_keys - report.keys()}"

    for gate_name, gate_info in report["gates"].items():
        status = gate_info.get("status")
        assert status == "PASS", f"Gate {gate_name} did not pass (status={status})"

    assert report.get("blockers", 0) == 0, f"Blockers present: {report.get('blockers')}"
    assert "PASS" in report.get("summary", ""), "Report summary does not indicate PASS"

    # If we reach this point, the system‑level test passes according to SCP DNA.

# The test is deliberately simple but exhaustive: it checks concrete runtime evidence
# rather than relying on mocked unit‑test expectations. This aligns with the user
# request to evaluate the *actual* outcome of the previous work.
