#!/usr/bin/env python3
"""Reality test for Fix 4-d-024: pending_fixes/ has README with review process.

DNA #4 (Con người quyết định — human review step is non-functional) + #8
(KB accumulation — audit decisions parked without action) + #11 (Human-
in-the-loop thật — no real human review).

Before fix:
  - `pending_fixes/` contained 3 .py files generated by SCP's autofix
    engine when it couldn't auto-parse the LLM fix into a safe patch.
  - Each was a comment-only stub. There was NO dashboard UI, NO email
    notification, NO CI check, NO README documenting the review process.
  - The fixes sat there indefinitely — "human review" was rubber-stamp-
    or-ignore (DNA #11 violation).

After fix (process gap, not code bug):
  - `pending_fixes/README.md` documents:
    (1) what pending_fixes/ is for,
    (2) how to review each file (read, decide approve/reject/defer, apply),
    (3) a weekly reminder to check.
  - Lists the 3 currently-pending files explicitly.

Tier-A (file-presence + content) reality test.
"""
import sys
from pathlib import Path

README_PATH = Path(
    str(Path(__file__).resolve().parents[2]) + '/pending_fixes/README.md'
)
PENDING_DIR = Path(
    str(Path(__file__).resolve().parents[2]) + '/pending_fixes'
)


def main() -> int:
    assert README_PATH.exists(), (
        f"FAIL: {README_PATH} does not exist — no human-review documentation "
        "(DNA #4 + #11 violation persists)"
    )
    print(f"PASS [1/4]: {README_PATH.name} exists")

    content = README_PATH.read_text(encoding="utf-8")
    assert content.strip(), f"FAIL: {README_PATH} is empty"
    print(f"PASS [2/4]: README is non-empty ({len(content)} chars)")

    # -------------------------------------------------------------------------
    # TEST 3 — README must document the review process. Look for keywords
    # indicating instructions: "review", "approve", "reject", "apply".
    # -------------------------------------------------------------------------
    has_review_kw = "review" in content.lower()
    has_decide_kw = (
        "approve" in content.lower()
        or "reject" in content.lower()
        or "defer" in content.lower()
    )
    has_apply_kw = (
        "apply" in content.lower()
        or "manually" in content.lower()
    )
    assert has_review_kw, (
        "FAIL: README doesn't mention 'review' — review process not documented"
    )
    assert has_decide_kw, (
        "FAIL: README doesn't mention 'approve' / 'reject' / 'defer' — "
        "no decision options documented"
    )
    assert has_apply_kw, (
        "FAIL: README doesn't mention 'apply' / 'manually' — no instructions "
        "for HOW to action an approved fix"
    )
    print("PASS [3/4]: README documents review + approve/reject + apply process")

    # -------------------------------------------------------------------------
    # TEST 4 — README must mention at least the review process (or the 3
    # pending files explicitly). We check that it references the pending
    # files (filenames or counts) so it's actually grounded in reality.
    # -------------------------------------------------------------------------
    # List the actual pending files in the directory.
    pending_files = sorted(
        f.name for f in PENDING_DIR.iterdir()
        if f.is_file() and f.name.endswith(".py")
    )
    assert pending_files, (
        "FAIL: no .py pending fix files in pending_fixes/ — test setup issue "
        "(the 3 expected files are missing)"
    )
    # README must mention at least one of the pending filenames OR the
    # count "3" (the number of pending files at time of fix).
    mentions_specific_file = any(
        fname in content for fname in pending_files
    )
    mentions_count = "3 " in content or "3\n" in content or "three" in content.lower()
    assert mentions_specific_file or mentions_count, (
        f"FAIL: README doesn't reference any specific pending file ({pending_files}) "
        f"or the count 3 — documentation not grounded in reality"
    )
    print(
        f"PASS [4/4]: README references pending files ({len(pending_files)} in dir, "
        f"mentioned={mentions_specific_file or mentions_count})"
    )

    print("\n✓ Reality test 4-d-024 PASSED (4/4 assertions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
