flowchart LR
    n0["scp<br/>7 lines"]
    n1["scp.__main__<br/>120 lines"]
    n2["scp.ai_patterns<br/>453 lines"]
    n3["scp.api<br/>1 lines"]
    n4["scp.api._lifespan<br/>757 lines"]
    n5["scp.api._shared<br/>131 lines"]
    n6["scp.api.chat<br/>338 lines"]
    n7["scp.api.dashboard_html<br/>541 lines"]
    n8["scp.api.routes<br/>11 lines"]
    n9["scp.api.routes.admin_v100<br/>150 lines"]
    n10["scp.api.routes.admin_v98<br/>122 lines"]
    n11["scp.api.routes.agent_routes<br/>153 lines"]
    n12["scp.api.routes.audit_routes<br/>54 lines"]
    n13["scp.api.routes.batch_benchmark_routes<br/>329 lines"]
    n14["scp.api.routes.call_routes<br/>55 lines"]
    n15["scp.api.routes.control_routes<br/>141 lines"]
    n16["scp.api.routes.hands_routes<br/>253 lines"]
    n17["scp.api.routes.import_routes<br/>191 lines"]
    n18["scp.api.routes.openai_compat<br/>140 lines"]
    n19["scp.api.routes.pc_controller_routes<br/>112 lines"]
    n20["scp.api.routes.prediction_routes<br/>115 lines"]
    n21["scp.api.routes.stream_routes<br/>97 lines"]
    n22["scp.api.routes.threat_routes<br/>72 lines"]
    n23["scp.api.routes.v102_v103_routes<br/>141 lines"]
    n24["scp.api.routes.v104_routes<br/>374 lines"]
    n25["scp.api.routes.v105_routes<br/>701 lines"]
    n26["scp.api.routes.web_control_routes<br/>120 lines"]
    n27["scp.api.webhook<br/>234 lines"]
    n28["scp.api_server<br/>1954 lines"]
    n29["scp.api_server_parts<br/>2 lines"]
    n30["scp.api_server_parts.helpers<br/>406 lines"]
    n31["scp.ask_kernel_adapter<br/>365 lines"]
    n32["scp.autofix<br/>32 lines"]
    n33["scp.autofix.ast_diff_cache<br/>413 lines"]
    n34["scp.autofix.audit_log<br/>344 lines"]
    n35["scp.autofix.bug_report_validator<br/>478 lines"]
    n36["scp.autofix.callgraph_delta<br/>735 lines"]
    n37["scp.autofix.classifier<br/>307 lines"]
    n38["scp.autofix.concurrent_runner<br/>285 lines"]
    n39["scp.autofix.confidence_ranker<br/>412 lines"]
    n40["scp.autofix.deterministic_patches<br/>374 lines"]
    n41["scp.autofix.deterministic_worker<br/>538 lines"]
    n42["scp.autofix.diagnostic<br/>131 lines"]
    n43["scp.autofix.engine<br/>2715 lines"]
    n44["scp.autofix.engine_extensions<br/>599 lines"]
    n45["scp.autofix.enterprise_scanners<br/>710 lines"]
    n46["scp.autofix.evidence_replay<br/>649 lines"]
    n47["scp.autofix.evolution<br/>605 lines"]
    n48["scp.autofix.evolution_modes<br/>189 lines"]
    n49["scp.autofix.evolution_modes.pattern_fixers<br/>219 lines"]
    n50["scp.autofix.evolution_parts<br/>2 lines"]
    n51["scp.autofix.evolution_parts.buildmixin<br/>378 lines"]
    n52["scp.autofix.evolution_parts.reflectmixin<br/>606 lines"]
    n53["scp.autofix.evolution_parts.wiremixin<br/>141 lines"]
    n54["scp.autofix.intent_inference_engine<br/>512 lines"]
    n55["scp.autofix.llm_fix<br/>1045 lines"]
    n56["scp.autofix.llm_fix_cache<br/>504 lines"]
    n57["scp.autofix.monitor<br/>187 lines"]
    n58["scp.autofix.parallel_scanner<br/>429 lines"]
    n59["scp.autofix.permission<br/>357 lines"]
    n60["scp.autofix.policy_gate<br/>851 lines"]
    n61["scp.autofix.property_validator<br/>914 lines"]
    n62["scp.autofix.realtime_verifier<br/>403 lines"]
    n63["scp.autofix.restricted_exec<br/>71 lines"]
    n64["scp.autofix.rollback_registry<br/>118 lines"]
    n65["scp.autofix.runner<br/>728 lines"]
    n66["scp.autofix.runner_phases<br/>101 lines"]
    n67["scp.autofix.runner_phases.ast_scan<br/>766 lines"]
    n68["scp.autofix.runner_phases.auto_rollback<br/>576 lines"]
    n69["scp.autofix.runner_phases.blast_radius<br/>373 lines"]
    n70["scp.autofix.runner_phases.completeness_check<br/>252 lines"]
    n71["scp.autofix.runner_phases.diff_rescan<br/>261 lines"]
    n72["scp.autofix.runner_phases.lineage_cross_validation<br/>237 lines"]
    n73["scp.autofix.runner_phases.permission_check<br/>125 lines"]
    n74["scp.autofix.runner_phases.post_fix_verify<br/>584 lines"]
    n75["scp.autofix.runner_phases.pre_startup<br/>177 lines"]
    n76["scp.autofix.runner_phases.reality_test<br/>345 lines"]
    n77["scp.autofix.runner_phases.report<br/>272 lines"]
    n78["scp.autofix.runner_phases.semantic_equiv<br/>398 lines"]
    n79["scp.autofix.runner_phases.shadow_canary<br/>756 lines"]
    n80["scp.autofix.scanners<br/>151 lines"]
    n81["scp.autofix.scanners._self_audit<br/>534 lines"]
    n82["scp.autofix.scanners.api_wiring_scanner<br/>230 lines"]
    n83["scp.autofix.scanners.cross_func_taint_scanner<br/>1254 lines"]
    n84["scp.autofix.scanners.dead_code_scanner<br/>427 lines"]
    n85["scp.autofix.scanners.dead_slm_scanner<br/>220 lines"]
    n86["scp.autofix.scanners.hypothesis_scanner<br/>403 lines"]
    n87["scp.autofix.scanners.logic_flow_scanner<br/>214 lines"]
    n88["scp.autofix.scanners.null_safety_scanner<br/>334 lines"]
    n89["scp.autofix.scanners.performance_scanner<br/>331 lines"]
    n90["scp.autofix.scanners.race_condition_scanner<br/>511 lines"]
    n91["scp.autofix.scanners.resource_leak_scanner<br/>295 lines"]
    n92["scp.autofix.scanners.routing_gap_scanner<br/>229 lines"]
    n93["scp.autofix.scanners.schema_scanner<br/>235 lines"]
    n94["scp.autofix.scanners.security_scanner<br/>338 lines"]
    n95["scp.autofix.scanners.semantic_intent_scanner<br/>640 lines"]
    n96["scp.autofix.scanners.sql_injection_scanner<br/>286 lines"]
    n97["scp.autofix.scanners.staticmethod_self_scanner<br/>150 lines"]
    n98["scp.autofix.scanners.taint_flow_scanner<br/>830 lines"]
    n99["scp.autofix.scanners.type_contract_scanner<br/>337 lines"]
    n100["scp.autofix.scanners.xss_scanner<br/>579 lines"]
    n101["scp.autofix.speculative_prefixer<br/>839 lines"]
    n102["scp.autofix.type_flow_verifier<br/>802 lines"]
    n103["scp.autofix.validate_patch<br/>179 lines"]
    n104["scp.benchmark.compare_results<br/>189 lines"]
    n105["scp.benchmark.question_generator<br/>360 lines"]
    n106["scp.benchmark.run_baseline<br/>272 lines"]
    n107["scp.benchmark.run_benchmark<br/>260 lines"]
    n108["scp.benchmark.run_benchmark_enhanced<br/>520 lines"]
    n109["scp.benchmark.run_benchmark_v2<br/>1010 lines"]
    n110["scp.brain<br/>21 lines"]
    n111["scp.brain.brain<br/>39 lines"]
    n112["scp.brain.error_store<br/>548 lines"]
    n113["scp.brain.error_store_index<br/>535 lines"]
    n114["scp.brain.index_parts<br/>85 lines"]
    n115["scp.brain.index_parts.clustering<br/>239 lines"]
    n116["scp.brain.index_parts.retrieval<br/>419 lines"]
    n117["scp.brain.index_parts.similarity<br/>241 lines"]
    n118["scp.capabilities<br/>19 lines"]
    n119["scp.capabilities.rag<br/>48 lines"]
    n120["scp.capabilities.vector_db<br/>88 lines"]
    n121["scp.capabilities.vision<br/>47 lines"]
    n122["scp.capabilities.voice<br/>80 lines"]
    n123["scp.consolidator<br/>6 lines"]
    n124["scp.consolidator.consolidator<br/>155 lines"]
    n125["scp.core<br/>55 lines"]
    n126["scp.core.agent_autofix_adapter<br/>315 lines"]
    n127["scp.core.agent_orchestrator<br/>272 lines"]
    n128["scp.core.ai_threat_scanner<br/>294 lines"]
    n129["scp.core.anchor<br/>210 lines"]
    n130["scp.core.antibody<br/>146 lines"]
    n131["scp.core.api_utils<br/>221 lines"]
    n132["scp.core.audit_fetcher<br/>230 lines"]
    n133["scp.core.auto_backup<br/>294 lines"]
    n134["scp.core.bounded_evolution<br/>219 lines"]
    n135["scp.core.call_session_hub<br/>159 lines"]
    n136["scp.core.chat_memory_store<br/>140 lines"]
    n137["scp.core.circuit_breaker<br/>432 lines"]
    n138["scp.core.code_evolution_agent<br/>586 lines"]
    n139["scp.core.conflict_resolver<br/>528 lines"]
    n140["scp.core.cross_verify<br/>401 lines"]
    n141["scp.core.crypto_verifier<br/>471 lines"]
    n142["scp.core.data_partitioner<br/>238 lines"]
    n143["scp.core.db_manager<br/>1127 lines"]
    n144["scp.core.evidence_filter<br/>155 lines"]
    n145["scp.core.fast_learning_engine<br/>1507 lines"]
    n146["scp.core.generator<br/>58 lines"]
    n147["scp.core.github_backup<br/>198 lines"]
    n148["scp.core.harm_detector<br/>239 lines"]
    n149["scp.core.healing_engine<br/>138 lines"]
    n150["scp.core.hypothesis_zone<br/>301 lines"]
    n151["scp.core.kham_pha_logger<br/>177 lines"]
    n152["scp.core.knowledge_io<br/>73 lines"]
    n153["scp.core.learning_run_ledger<br/>188 lines"]
    n154["scp.core.math_evaluator<br/>521 lines"]
    n155["scp.core.memory_manager<br/>74 lines"]
    n156["scp.core.multi_source_verifier<br/>668 lines"]
    n157["scp.core.partition<br/>60 lines"]
    n158["scp.core.partition.archive<br/>425 lines"]
    n159["scp.core.partition.rotate<br/>310 lines"]
    n160["scp.core.partition.shard<br/>521 lines"]
    n161["scp.core.phase0<br/>693 lines"]
    n162["scp.core.policy_materializer<br/>295 lines"]
    n163["scp.core.question_fetchers<br/>16 lines"]
    n164["scp.core.question_fetchers._common<br/>264 lines"]
    n165["scp.core.question_fetchers.data_fetchers<br/>536 lines"]
    n166["scp.core.question_fetchers.knowledge_fetchers<br/>254 lines"]
    n167["scp.core.question_fetchers.trivia_fetchers<br/>282 lines"]
    n168["scp.core.question_normalizer<br/>426 lines"]
    n169["scp.core.react_agent<br/>215 lines"]
    n170["scp.core.real_learning_engine<br/>102 lines"]
    n171["scp.core.real_question_fetcher<br/>325 lines"]
    n172["scp.core.reality_engine<br/>325 lines"]
    n173["scp.core.release_identity<br/>48 lines"]
    n174["scp.core.request_run_ledger<br/>314 lines"]
    n175["scp.core.safe_process<br/>209 lines"]
    n176["scp.core.scp_v14<br/>39 lines"]
    n177["scp.core.smart_cache<br/>607 lines"]
    n178["scp.core.smart_classifier<br/>439 lines"]
    n179["scp.core.startup_optimizer<br/>319 lines"]
    n180["scp.core.streaming_factcheck<br/>264 lines"]
    n181["scp.core.subsystem_telemetry<br/>403 lines"]
    n182["scp.core.url_fetcher<br/>209 lines"]
    n183["scp.core.wikipedia_client<br/>287 lines"]
    n184["scp.data_sources<br/>200 lines"]
    n185["scp.data_sources._matching<br/>35 lines"]
    n186["scp.data_sources.aerospace<br/>76 lines"]
    n187["scp.data_sources.agriculture<br/>226 lines"]
    n188["scp.data_sources.alphavantage<br/>157 lines"]
    n189["scp.data_sources.architecture<br/>57 lines"]
    n190["scp.data_sources.arts<br/>214 lines"]
    n191["scp.data_sources.astronomy<br/>486 lines"]
    n192["scp.data_sources.audiovideo<br/>57 lines"]
    n193["scp.data_sources.biology<br/>245 lines"]
    n194["scp.data_sources.blockchain<br/>108 lines"]
    n195["scp.data_sources.cartography<br/>70 lines"]
    n196["scp.data_sources.chemistry<br/>621 lines"]
    n197["scp.data_sources.conversion<br/>303 lines"]
    n198["scp.data_sources.cornell_lii<br/>140 lines"]
    n199["scp.data_sources.courtlistener<br/>118 lines"]
    n200["scp.data_sources.crafts<br/>56 lines"]
    n201["scp.data_sources.cybersecurity<br/>260 lines"]
    n202["scp.data_sources.digitalmarketing<br/>56 lines"]
    n203["scp.data_sources.diplomacy<br/>59 lines"]
    n204["scp.data_sources.domain_classifier<br/>285 lines"]
    n205["scp.data_sources.domain_registry<br/>1075 lines"]
    n206["scp.data_sources.dtic<br/>137 lines"]
    n207["scp.data_sources.ecommerce<br/>56 lines"]
    n208["scp.data_sources.education<br/>130 lines"]
    n209["scp.data_sources.energy<br/>201 lines"]
    n210["scp.data_sources.environment<br/>141 lines"]
    n211["scp.data_sources.eric<br/>136 lines"]
    n212["scp.data_sources.finance<br/>247 lines"]
    n213["scp.data_sources.foodtech<br/>55 lines"]
    n214["scp.data_sources.fred<br/>124 lines"]
    n215["scp.data_sources.genai<br/>125 lines"]
    n216["scp.data_sources.geography<br/>202 lines"]
    n217["scp.data_sources.geology<br/>135 lines"]
    n218["scp.data_sources.glottolog<br/>187 lines"]
    n219["scp.data_sources.google_factcheck<br/>124 lines"]
    n220["scp.data_sources.gutenberg<br/>140 lines"]
    n221["scp.data_sources.heritage<br/>150 lines"]
    n222["scp.data_sources.history<br/>263 lines"]
    n223["scp.data_sources.legal<br/>300 lines"]
    n224["scp.data_sources.live_knowledge<br/>696 lines"]
    n225["scp.data_sources.logic<br/>150 lines"]
    n226["scp.data_sources.math<br/>102 lines"]
    n227["scp.data_sources.medical<br/>418 lines"]
    n228["scp.data_sources.metmuseum<br/>143 lines"]
    n229["scp.data_sources.military<br/>157 lines"]
    n230["scp.data_sources.newsapi<br/>95 lines"]
    n231["scp.data_sources.noaa<br/>166 lines"]
    n232["scp.data_sources.oceanography<br/>56 lines"]
    n233["scp.data_sources.physics<br/>171 lines"]
    n234["scp.data_sources.psychology<br/>116 lines"]
    n235["scp.data_sources.reality<br/>240 lines"]
    n236["scp.data_sources.registry<br/>168 lines"]
    n237["scp.data_sources.religion<br/>67 lines"]
    n238["scp.data_sources.social<br/>58 lines"]
    n239["scp.data_sources.spacemedicine<br/>80 lines"]
    n240["scp.data_sources.sports<br/>243 lines"]
    n241["scp.data_sources.statistics<br/>165 lines"]
    n242["scp.data_sources.technology<br/>249 lines"]
    n243["scp.data_sources.tourism<br/>78 lines"]
    n244["scp.data_sources.transport<br/>56 lines"]
    n245["scp.data_sources.undata<br/>144 lines"]
    n246["scp.data_sources.unesco<br/>170 lines"]
    n247["scp.data_sources.usgs<br/>190 lines"]
    n248["scp.data_sources.uxui<br/>55 lines"]
    n249["scp.data_sources.weather<br/>191 lines"]
    n250["scp.data_sources.wikiart<br/>206 lines"]
    n251["scp.data_sources.worldbank<br/>151 lines"]
    n252["scp.experience<br/>6 lines"]
    n253["scp.experience.experience<br/>820 lines"]
    n254["scp.forecast<br/>20 lines"]
    n255["scp.forecast.ledger<br/>296 lines"]
    n256["scp.forecast.scoring<br/>88 lines"]
    n257["scp.foundation<br/>9 lines"]
    n258["scp.foundation.batch<br/>248 lines"]
    n259["scp.foundation.parser<br/>205 lines"]
    n260["scp.hands<br/>8 lines"]
    n261["scp.hands.action_registry<br/>84 lines"]
    n262["scp.hands.goal_parser<br/>171 lines"]
    n263["scp.hands.hands_executor<br/>390 lines"]
    n264["scp.hands.planner<br/>871 lines"]
    n265["scp.hands.process_manager<br/>111 lines"]
    n266["scp.hands.process_probe<br/>7 lines"]
    n267["scp.hands.task_kernel_bridge<br/>316 lines"]
    n268["scp.history<br/>14 lines"]
    n269["scp.history.evidence_ledger<br/>96 lines"]
    n270["scp.history.migration<br/>283 lines"]
    n271["scp.history.regression_corpus<br/>169 lines"]
    n272["scp.history.semantic_gate<br/>96 lines"]
    n273["scp.interfaces<br/>9 lines"]
    n274["scp.interfaces.data_source<br/>76 lines"]
    n275["scp.knowledge<br/>1 lines"]
    n276["scp.knowledge.antibody_system<br/>1767 lines"]
    n277["scp.knowledge.claim_extractor<br/>434 lines"]
    n278["scp.knowledge.cwe_exploit_store<br/>299 lines"]
    n279["scp.knowledge.domain_store<br/>494 lines"]
    n280["scp.knowledge.scheduled_crawler<br/>336 lines"]
    n281["scp.knowledge.source_reputation<br/>696 lines"]
    n282["scp.knowledge.source_watchlist<br/>296 lines"]
    n283["scp.knowledge.trust_hierarchy<br/>219 lines"]
    n284["scp.llm_gateway<br/>23 lines"]
    n285["scp.llm_gateway.client<br/>737 lines"]
    n286["scp.meta<br/>8 lines"]
    n287["scp.meta._number_utils<br/>112 lines"]
    n288["scp.meta.adversary_verifier<br/>550 lines"]
    n289["scp.meta.anti_closure_meta<br/>128 lines"]
    n290["scp.meta.behavior_monitor<br/>451 lines"]
    n291["scp.meta.calibration_engine<br/>606 lines"]
    n292["scp.meta.capability_levels<br/>222 lines"]
    n293["scp.meta.cognitive_engine<br/>335 lines"]
    n294["scp.meta.cognitive_gate<br/>413 lines"]
    n295["scp.meta.cognitive_layers<br/>55 lines"]
    n296["scp.meta.cognitive_layers.counter_question<br/>185 lines"]
    n297["scp.meta.cognitive_layers.meta_falsifier<br/>308 lines"]
    n298["scp.meta.cognitive_layers.proof_graph<br/>210 lines"]
    n299["scp.meta.cognitive_layers.recursive_why<br/>378 lines"]
    n300["scp.meta.cognitive_layers.unknown_state<br/>188 lines"]
    n301["scp.meta.constitution<br/>186 lines"]
    n302["scp.meta.curiosity_asker<br/>74 lines"]
    n303["scp.meta.external_trust<br/>313 lines"]
    n304["scp.meta.falsification_engine<br/>982 lines"]
    n305["scp.meta.governance_v97<br/>255 lines"]
    n306["scp.meta.kb_evolve<br/>459 lines"]
    n307["scp.meta.knowledge_arbiter<br/>260 lines"]
    n308["scp.meta.logical_auditor<br/>319 lines"]
    n309["scp.meta.meta<br/>954 lines"]
    n310["scp.meta.meta_schema<br/>120 lines"]
    n311["scp.meta.metawhy_monitor<br/>209 lines"]
    n312["scp.meta.multi_llm_check<br/>230 lines"]
    n313["scp.meta.policy_applier<br/>494 lines"]
    n314["scp.meta.principle_rules<br/>489 lines"]
    n315["scp.meta.question_tracker<br/>459 lines"]
    n316["scp.meta.reverify_scheduler<br/>315 lines"]
    n317["scp.meta.scp_meta<br/>73 lines"]
    n318["scp.meta.self_questioning<br/>396 lines"]
    n319["scp.meta.severity<br/>23 lines"]
    n320["scp.meta.simple_explainer<br/>154 lines"]
    n321["scp.meta.understanding_check<br/>107 lines"]
    n322["scp.meta.verdict_predictor<br/>397 lines"]
    n323["scp.meta.why_engine<br/>1087 lines"]
    n324["scp.meta.why_engine_cli<br/>73 lines"]
    n325["scp.meta.why_execute_plan<br/>210 lines"]
    n326["scp.meta.why_gate<br/>562 lines"]
    n327["scp.meta.why_sources<br/>20 lines"]
    n328["scp.meta.why_sources.crypto<br/>37 lines"]
    n329["scp.meta.why_sources.frankfurter<br/>37 lines"]
    n330["scp.meta.why_sources.nasa<br/>30 lines"]
    n331["scp.meta.why_sources.open_meteo<br/>42 lines"]
    n332["scp.meta.why_sources.pubchem<br/>32 lines"]
    n333["scp.meta.why_sources.rest_countries<br/>48 lines"]
    n334["scp.meta.why_sources.wikidata<br/>34 lines"]
    n335["scp.meta.why_sources.wikipedia<br/>293 lines"]
    n336["scp.meta.why_v80_modes<br/>370 lines"]
    n337["scp.observability<br/>6 lines"]
    n338["scp.observability.otel<br/>51 lines"]
    n339["scp.pc_control<br/>6 lines"]
    n340["scp.pc_control.pc_controller<br/>295 lines"]
    n341["scp.prediction<br/>6 lines"]
    n342["scp.prediction.predictive<br/>951 lines"]
    n343["scp.rag<br/>2 lines"]
    n344["scp.rag.canonical_retriever<br/>72 lines"]
    n345["scp.runtime<br/>49 lines"]
    n346["scp.runtime.engine<br/>575 lines"]
    n347["scp.runtime.engine_parts<br/>2 lines"]
    n348["scp.runtime.engine_parts.direct_api_verifier<br/>401 lines"]
    n349["scp.runtime.engine_parts.scpv14_process_mixin<br/>651 lines"]
    n350["scp.runtime.healing_v14<br/>391 lines"]
    n351["scp.runtime.judge<br/>1384 lines"]
    n352["scp.runtime.judge_parts<br/>2 lines"]
    n353["scp.runtime.judge_parts.judge_phase_4_governance<br/>1 lines"]
    n354["scp.runtime.judge_parts.judge_phases<br/>362 lines"]
    n355["scp.runtime.judge_parts.judgebg_mixin<br/>176 lines"]
    n356["scp.runtime.judge_parts.judgecore_mixin<br/>3523 lines"]
    n357["scp.runtime.judge_parts.judgeroute_mixin<br/>542 lines"]
    n358["scp.runtime.judge_parts.judgeutil_mixin<br/>177 lines"]
    n359["scp.runtime.judge_parts.types<br/>42 lines"]
    n360["scp.runtime.notifications<br/>324 lines"]
    n361["scp.runtime.orchestrator<br/>24 lines"]
    n362["scp.runtime.parallel_pipeline<br/>165 lines"]
    n363["scp.runtime.safe_math<br/>52 lines"]
    n364["scp.runtime.slm_base<br/>230 lines"]
    n365["scp.runtime.slm_impls<br/>17 lines"]
    n366["scp.runtime.slm_impls.agriculture_slm<br/>140 lines"]
    n367["scp.runtime.slm_impls.art_slm<br/>143 lines"]
    n368["scp.runtime.slm_impls.chem_reality_astro_slm<br/>818 lines"]
    n369["scp.runtime.slm_impls.economics_slm<br/>145 lines"]
    n370["scp.runtime.slm_impls.education_slm<br/>142 lines"]
    n371["scp.runtime.slm_impls.engineering_slm<br/>163 lines"]
    n372["scp.runtime.slm_impls.humanities_slm<br/>821 lines"]
    n373["scp.runtime.slm_impls.law_slm<br/>146 lines"]
    n374["scp.runtime.slm_impls.lifestyle_slm<br/>656 lines"]
    n375["scp.runtime.slm_impls.literature_slm<br/>173 lines"]
    n376["scp.runtime.slm_impls.management_slm<br/>137 lines"]
    n377["scp.runtime.slm_impls.math_biology_slm<br/>393 lines"]
    n378["scp.runtime.slm_impls.military_slm<br/>144 lines"]
    n379["scp.runtime.slm_impls.misc_slm<br/>667 lines"]
    n380["scp.runtime.slm_impls.numeric_data_slm<br/>453 lines"]
    n381["scp.runtime.slm_impls.philosophy_slm<br/>142 lines"]
    n382["scp.runtime.slms<br/>556 lines"]
    n383["scp.runtime.slms_parts<br/>2 lines"]
    n384["scp.runtime.slms_parts._domainslm<br/>332 lines"]
    n385["scp.runtime.slms_parts.astronomyslm<br/>295 lines"]
    n386["scp.runtime.slms_parts.biologyslm<br/>371 lines"]
    n387["scp.runtime.slms_parts.chemistryslm<br/>333 lines"]
    n388["scp.runtime.slms_parts.conversionslm<br/>371 lines"]
    n389["scp.runtime.slms_parts.entertainmentslm<br/>381 lines"]
    n390["scp.runtime.slms_parts.foodslm<br/>271 lines"]
    n391["scp.runtime.slms_parts.generalslm<br/>268 lines"]
    n392["scp.runtime.slms_parts.geographyslm<br/>635 lines"]
    n393["scp.runtime.slms_parts.historyslm<br/>528 lines"]
    n394["scp.runtime.slms_parts.mathslm<br/>279 lines"]
    n395["scp.runtime.slms_parts.misc_slms2<br/>889 lines"]
    n396["scp.runtime.slms_parts.realityslm<br/>434 lines"]
    n397["scp.runtime.slms_parts.universalslm<br/>343 lines"]
    n398["scp.runtime.slms_parts.weatherslm<br/>276 lines"]
    n399["scp.runtime.storage_manager<br/>517 lines"]
    n400["scp.runtime.timing_and_restart<br/>127 lines"]
    n401["scp.security<br/>1 lines"]
    n402["scp.security.attack_classifier<br/>173 lines"]
    n403["scp.security.attack_crawler<br/>459 lines"]
    n404["scp.security.attack_memory<br/>511 lines"]
    n405["scp.security.attack_policy<br/>172 lines"]
    n406["scp.security.auth<br/>178 lines"]
    n407["scp.security.auth_config<br/>107 lines"]
    n408["scp.security.auto_payload_generator<br/>251 lines"]
    n409["scp.security.bypass_encrypt<br/>275 lines"]
    n410["scp.security.canary_monitor<br/>277 lines"]
    n411["scp.security.capability_epoch<br/>145 lines"]
    n412["scp.security.circuit_breaker<br/>161 lines"]
    n413["scp.security.cisa_kev<br/>207 lines"]
    n414["scp.security.counter_response<br/>686 lines"]
    n415["scp.security.cross_language_learner<br/>247 lines"]
    n416["scp.security.dos_protection<br/>291 lines"]
    n417["scp.security.env_loader<br/>41 lines"]
    n418["scp.security.escalation<br/>497 lines"]
    n419["scp.security.gcg_attack<br/>197 lines"]
    n420["scp.security.h8_redteam_bridge<br/>656 lines"]
    n421["scp.security.image_voice_detector<br/>344 lines"]
    n422["scp.security.memory_guard<br/>230 lines"]
    n423["scp.security.multi_turn_tracker<br/>280 lines"]
    n424["scp.security.playbooks<br/>100 lines"]
    n425["scp.security.predictor<br/>557 lines"]
    n426["scp.security.production_guard<br/>48 lines"]
    n427["scp.security.provider_keys<br/>71 lines"]
    n428["scp.security.response_monitor<br/>403 lines"]
    n429["scp.security.rogue_ai_detector<br/>228 lines"]
    n430["scp.security.secret_loader<br/>17 lines"]
    n431["scp.security.threat_detector<br/>609 lines"]
    n432["scp.security.threat_intel<br/>354 lines"]
    n433["scp.security.threat_simulator<br/>519 lines"]
    n434["scp.security.unified_detector<br/>483 lines"]
    n435["scp.security.url_safety<br/>85 lines"]
    n436["scp.task_kernel<br/>951 lines"]
    n437["scp.tests<br/>2 lines"]
    n438["scp.tests.external_audit<br/>16 lines"]
    n439["scp.tests.external_audit.conftest<br/>35 lines"]
    n440["scp.tests.external_audit.test_cascade<br/>231 lines"]
    n441["scp.tests.external_audit.test_security<br/>216 lines"]
    n442["scp.tests.property<br/>1 lines"]
    n443["scp.tests.property.test_none_safety<br/>252 lines"]
    n444["scp.tests.test_judge_characterization<br/>167 lines"]
    n445["scp.trace_ledger<br/>48 lines"]
    n446["scp.verifier<br/>69 lines"]
    n447["scp.web_control<br/>8 lines"]
    n448["scp.web_control.ai_orchestrator<br/>110 lines"]
    n449["scp.web_control.browser_session<br/>158 lines"]
    n450["scp.web_control.internet_search<br/>141 lines"]
    n451["scp.web_control.multi_source_orchestrator<br/>76 lines"]
    n452["scp.web_control.web_navigator<br/>44 lines"]
    n0 --> n173
    n1 --> n426
    n4 --> n181
    n4 --> n173
    n4 --> n132
    n4 --> n128
    n4 --> n148
    n4 --> n30
    n4 --> n65
    n4 --> n303
    n4 --> n43
    n4 --> n138
    n5 --> n406
    n5 --> n351
    n5 --> n0
    n6 --> n174
    n6 --> n136
    n6 --> n5
    n6 --> n173
    n6 --> n28
    n6 --> n127
    n6 --> n138
    n9 --> n5
    n9 --> n174
    n9 --> n276
    n10 --> n5
    n10 --> n174
    n11 --> n174
    n11 --> n127
    n12 --> n5
    n12 --> n174
    n12 --> n132
    n13 --> n16
    n13 --> n174
    n14 --> n135
    n14 --> n174
    n15 --> n5
    n15 --> n292
    n15 --> n30
    n16 --> n174
    n16 --> n262
    n16 --> n263
    n16 --> n264
    n16 --> n267
    n17 --> n5
    n17 --> n174
    n18 --> n5
    n18 --> n173
    n18 --> n174
    n19 --> n340
    n19 --> n174
    n20 --> n5
    n20 --> n174
    n20 --> n28
    n21 --> n5
    n21 --> n174
    n21 --> n178
    n22 --> n5
    n22 --> n174
    n22 --> n128
    n22 --> n148
    n23 --> n5
    n23 --> n174
    n23 --> n360
    n23 --> n399
    n23 --> n419
    n24 --> n5
    n24 --> n174
    n24 --> n170
    n25 --> n5
    n25 --> n181
    n25 --> n174
    n25 --> n43
    n25 --> n65
    n25 --> n41
    n25 --> n57
    n25 --> n177
    n25 --> n67
    n26 --> n448
    n26 --> n451
    n26 --> n452
    n26 --> n174
    n27 --> n174
    n27 --> n5
    n28 --> n417
    n28 --> n450
    n28 --> n30
    n28 --> n174
    n28 --> n0
    n28 --> n173
    n28 --> n180
    n28 --> n320
    n28 --> n351
    n28 --> n403
    n28 --> n415
    n28 --> n421
    n28 --> n423
    n28 --> n170
    n28 --> n342
    n28 --> n6
    n28 --> n145
    n28 --> n179
    n28 --> n142
    n28 --> n10
    n28 --> n9
    n28 --> n7
    n28 --> n17
    n28 --> n18
    n28 --> n23
    n28 --> n24
    n28 --> n25
    n28 --> n15
    n28 --> n21
    n28 --> n22
    n28 --> n12
    n28 --> n20
    n28 --> n27
    n28 --> n19
    n28 --> n26
    n28 --> n16
    n28 --> n13
    n28 --> n11
    n28 --> n14
    n28 --> n338
    n28 --> n65
    n28 --> n181
    n28 --> n43
    n28 --> n303
    n28 --> n31
    n28 --> n47
    n28 --> n284
    n28 --> n156
    n28 --> n184
    n30 --> n182
    n30 --> n406
    n30 --> n403
    n30 --> n170
    n30 --> n145
    n30 --> n179
    n30 --> n142
    n30 --> n415
    n30 --> n351
    n30 --> n342
    n30 --> n160
    n31 --> n436
    n31 --> n445
    n31 --> n30
    n31 --> n125
    n32 --> n37
    n32 --> n43
    n32 --> n59
    n35 --> n37
    n35 --> n54
    n38 --> n67
    n41 --> n34
    n41 --> n37
    n41 --> n40
    n41 --> n44
    n41 --> n60
    n41 --> n67
    n43 --> n37
    n43 --> n59
    n43 --> n44
    n43 --> n67
    n43 --> n57
    n43 --> n292
    n43 --> n326
    n43 --> n60
    n43 --> n138
    n43 --> n34
    n43 --> n65
    n43 --> n45
    n43 --> n61
    n43 --> n55
    n43 --> n39
    n43 --> n69
    n43 --> n79
    n43 --> n62
    n43 --> n42
    n43 --> n68
    n43 --> n47
    n43 --> n103
    n43 --> n56
    n43 --> n74
    n43 --> n102
    n45 --> n37
    n45 --> n175
    n47 --> n37
    n47 --> n43
    n47 --> n181
    n47 --> n51
    n47 --> n52
    n47 --> n53
    n47 --> n49
    n47 --> n65
    n51 --> n47
    n51 --> n292
    n51 --> n55
    n52 --> n153
    n52 --> n181
    n52 --> n37
    n52 --> n47
    n52 --> n65
    n52 --> n55
    n52 --> n306
    n52 --> n292
    n52 --> n323
    n52 --> n326
    n53 --> n37
    n55 --> n427
    n55 --> n37
    n55 --> n284
    n55 --> n56
    n55 --> n40
    n55 --> n101
    n55 --> n47
    n59 --> n37
    n59 --> n321
    n61 --> n63
    n62 --> n63
    n64 --> n44
    n65 --> n37
    n65 --> n43
    n65 --> n34
    n65 --> n67
    n65 --> n73
    n65 --> n75
    n65 --> n77
    n65 --> n55
    n65 --> n326
    n65 --> n36
    n65 --> n47
    n65 --> n38
    n65 --> n134
    n66 --> n67
    n66 --> n73
    n66 --> n75
    n66 --> n77
    n66 --> n74
    n66 --> n76
    n66 --> n70
    n66 --> n72
    n66 --> n71
    n67 --> n37
    n67 --> n33
    n67 --> n58
    n67 --> n45
    n68 --> n76
    n68 --> n44
    n74 --> n66
    n74 --> n76
    n74 --> n70
    n74 --> n32
    n76 --> n74
    n77 --> n37
    n77 --> n43
    n77 --> n67
    n77 --> n80
    n77 --> n55
    n77 --> n35
    n79 --> n76
    n79 --> n61
    n80 --> n82
    n80 --> n84
    n80 --> n85
    n80 --> n87
    n80 --> n88
    n80 --> n89
    n80 --> n90
    n80 --> n91
    n80 --> n92
    n80 --> n93
    n80 --> n94
    n80 --> n96
    n80 --> n99
    n80 --> n100
    n80 --> n86
    n80 --> n81
    n80 --> n83
    n80 --> n98
    n80 --> n95
    n80 --> n97
    n81 --> n37
    n82 --> n37
    n83 --> n37
    n83 --> n98
    n84 --> n37
    n85 --> n37
    n86 --> n37
    n87 --> n37
    n88 --> n37
    n89 --> n37
    n90 --> n37
    n91 --> n37
    n92 --> n37
    n92 --> n85
    n93 --> n37
    n94 --> n37
    n95 --> n37
    n95 --> n55
    n95 --> n45
    n95 --> n67
    n96 --> n37
    n97 --> n37
    n98 --> n37
    n99 --> n37
    n100 --> n37
    n109 --> n105
    n109 --> n277
    n110 --> n0
    n111 --> n112
    n113 --> n115
    n113 --> n116
    n113 --> n117
    n114 --> n115
    n114 --> n116
    n114 --> n117
    n115 --> n117
    n116 --> n115
    n116 --> n117
    n117 --> n115
    n119 --> n120
    n119 --> n284
    n121 --> n284
    n125 --> n0
    n126 --> n37
    n126 --> n174
    n126 --> n43
    n126 --> n55
    n127 --> n174
    n127 --> n126
    n127 --> n262
    n127 --> n263
    n127 --> n264
    n128 --> n414
    n129 --> n143
    n131 --> n182
    n131 --> n137
    n133 --> n143
    n134 --> n153
    n134 --> n181
    n134 --> n47
    n138 --> n175
    n138 --> n77
    n139 --> n143
    n140 --> n131
    n141 --> n131
    n141 --> n139
    n142 --> n158
    n142 --> n159
    n142 --> n160
    n145 --> n143
    n145 --> n153
    n145 --> n181
    n145 --> n284
    n145 --> n326
    n145 --> n281
    n145 --> n282
    n148 --> n414
    n149 --> n143
    n151 --> n143
    n155 --> n177
    n156 --> n131
    n156 --> n139
    n156 --> n177
    n157 --> n158
    n157 --> n159
    n157 --> n160
    n158 --> n160
    n158 --> n159
    n158 --> n143
    n159 --> n160
    n159 --> n143
    n160 --> n326
    n160 --> n409
    n161 --> n143
    n164 --> n435
    n164 --> n143
    n165 --> n164
    n166 --> n164
    n167 --> n164
    n170 --> n145
    n171 --> n164
    n171 --> n165
    n171 --> n166
    n171 --> n167
    n171 --> n143
    n172 --> n183
    n177 --> n143
    n177 --> n364
    n178 --> n205
    n184 --> n0
    n184 --> n268
    n186 --> n274
    n187 --> n131
    n187 --> n274
    n188 --> n274
    n189 --> n274
    n190 --> n185
    n190 --> n274
    n191 --> n183
    n191 --> n185
    n191 --> n274
    n192 --> n274
    n193 --> n131
    n193 --> n274
    n194 --> n274
    n195 --> n274
    n196 --> n274
    n197 --> n274
    n198 --> n274
    n199 --> n274
    n200 --> n274
    n201 --> n131
    n201 --> n274
    n202 --> n274
    n203 --> n274
    n204 --> n205
    n206 --> n274
    n207 --> n274
    n208 --> n274
    n209 --> n131
    n209 --> n274
    n210 --> n274
    n211 --> n274
    n212 --> n274
    n213 --> n274
    n214 --> n274
    n215 --> n274
    n216 --> n274
    n217 --> n131
    n217 --> n274
    n218 --> n274
    n219 --> n274
    n220 --> n274
    n221 --> n274
    n222 --> n183
    n222 --> n185
    n222 --> n274
    n223 --> n131
    n223 --> n185
    n223 --> n274
    n224 --> n143
    n224 --> n183
    n224 --> n205
    n225 --> n274
    n226 --> n274
    n227 --> n131
    n227 --> n274
    n228 --> n274
    n229 --> n274
    n230 --> n274
    n231 --> n274
    n232 --> n274
    n233 --> n274
    n234 --> n274
    n235 --> n274
    n236 --> n274
    n237 --> n274
    n238 --> n274
    n239 --> n274
    n240 --> n274
    n241 --> n274
    n242 --> n274
    n243 --> n274
    n244 --> n274
    n245 --> n274
    n246 --> n274
    n247 --> n274
    n248 --> n274
    n249 --> n274
    n250 --> n183
    n250 --> n274
    n251 --> n274
    n253 --> n143
    n253 --> n176
    n253 --> n162
    n254 --> n0
    n256 --> n255
    n257 --> n0
    n260 --> n0
    n262 --> n264
    n263 --> n340
    n263 --> n411
    n263 --> n452
    n263 --> n261
    n263 --> n265
    n264 --> n263
    n267 --> n436
    n268 --> n0
    n270 --> n152
    n273 --> n0
    n276 --> n319
    n279 --> n283
    n282 --> n281
    n284 --> n285
    n285 --> n427
    n288 --> n139
    n288 --> n131
    n288 --> n141
    n288 --> n172
    n288 --> n156
    n291 --> n143
    n293 --> n296
    n293 --> n297
    n293 --> n298
    n293 --> n299
    n293 --> n300
    n293 --> n323
    n294 --> n143
    n295 --> n296
    n295 --> n297
    n295 --> n298
    n295 --> n299
    n295 --> n300
    n296 --> n143
    n298 --> n143
    n300 --> n143
    n304 --> n287
    n305 --> n289
    n305 --> n301
    n305 --> n319
    n309 --> n143
    n309 --> n176
    n309 --> n310
    n309 --> n314
    n310 --> n143
    n313 --> n143
    n314 --> n143
    n315 --> n143
    n316 --> n143
    n316 --> n137
    n316 --> n346
    n322 --> n143
    n322 --> n154
    n323 --> n143
    n323 --> n328
    n323 --> n329
    n323 --> n330
    n323 --> n331
    n323 --> n332
    n323 --> n333
    n323 --> n334
    n323 --> n335
    n323 --> n324
    n323 --> n325
    n323 --> n336
    n323 --> n284
    n323 --> n382
    n323 --> n185
    n323 --> n311
    n324 --> n323
    n325 --> n143
    n325 --> n323
    n326 --> n55
    n326 --> n284
    n326 --> n290
    n326 --> n306
    n328 --> n435
    n329 --> n435
    n330 --> n435
    n331 --> n435
    n332 --> n435
    n333 --> n435
    n334 --> n435
    n335 --> n183
    n335 --> n435
    n337 --> n0
    n339 --> n0
    n342 --> n131
    n342 --> n143
    n342 --> n176
    n342 --> n146
    n342 --> n172
    n345 --> n0
    n346 --> n149
    n346 --> n176
    n346 --> n348
    n346 --> n350
    n346 --> n351
    n346 --> n349
    n346 --> n111
    n346 --> n125
    n346 --> n129
    n346 --> n130
    n346 --> n253
    n346 --> n124
    n346 --> n342
    n346 --> n161
    n346 --> n309
    n346 --> n259
    n346 --> n258
    n346 --> n184
    n349 --> n143
    n349 --> n351
    n349 --> n151
    n349 --> n131
    n349 --> n309
    n350 --> n143
    n351 --> n176
    n351 --> n382
    n351 --> n355
    n351 --> n356
    n351 --> n357
    n351 --> n358
    n351 --> n359
    n351 --> n138
    n351 --> n418
    n351 --> n425
    n351 --> n178
    n351 --> n253
    n351 --> n322
    n351 --> n313
    n351 --> n288
    n351 --> n291
    n351 --> n323
    n351 --> n342
    n351 --> n304
    n351 --> n112
    n351 --> n113
    n351 --> n281
    n351 --> n282
    n351 --> n399
    n351 --> n301
    n351 --> n305
    n351 --> n431
    n351 --> n402
    n351 --> n422
    n351 --> n429
    n351 --> n405
    n351 --> n414
    n351 --> n410
    n351 --> n404
    n351 --> n433
    n351 --> n432
    n351 --> n428
    n351 --> n279
    n351 --> n277
    n351 --> n420
    n351 --> n280
    n351 --> n308
    n351 --> n318
    n351 --> n416
    n351 --> n284
    n351 --> n169
    n351 --> n276
    n351 --> n434
    n351 --> n361
    n351 --> n360
    n351 --> n350
    n351 --> n316
    n351 --> n293
    n351 --> n307
    n351 --> n362
    n351 --> n354
    n351 --> n312
    n354 --> n434
    n355 --> n312
    n355 --> n143
    n355 --> n408
    n356 --> n143
    n356 --> n144
    n356 --> n359
    n356 --> n317
    n356 --> n400
    n356 --> n154
    n356 --> n326
    n356 --> n315
    n356 --> n278
    n356 --> n139
    n356 --> n2
    n356 --> n281
    n356 --> n294
    n356 --> n312
    n356 --> n304
    n356 --> n363
    n357 --> n205
    n357 --> n204
    n357 --> n312
    n360 --> n319
    n364 --> n168
    n364 --> n143
    n366 --> n364
    n366 --> n187
    n367 --> n364
    n367 --> n190
    n368 --> n143
    n368 --> n364
    n368 --> n177
    n368 --> n191
    n368 --> n196
    n368 --> n156
    n369 --> n364
    n369 --> n214
    n369 --> n251
    n370 --> n364
    n370 --> n211
    n371 --> n364
    n372 --> n364
    n372 --> n435
    n372 --> n177
    n372 --> n131
    n373 --> n364
    n373 --> n223
    n374 --> n364
    n374 --> n435
    n374 --> n172
    n374 --> n140
    n375 --> n364
    n375 --> n220
    n376 --> n364
    n377 --> n364
    n377 --> n435
    n377 --> n154
    n377 --> n177
    n378 --> n364
    n378 --> n229
    n379 --> n364
    n379 --> n435
    n379 --> n177
    n379 --> n172
    n379 --> n197
    n379 --> n140
    n379 --> n141
    n379 --> n216
    n380 --> n131
    n380 --> n364
    n380 --> n154
    n380 --> n177
    n380 --> n141
    n380 --> n156
    n381 --> n364
    n382 --> n384
    n382 --> n390
    n382 --> n395
    n382 --> n366
    n382 --> n367
    n382 --> n368
    n382 --> n369
    n382 --> n370
    n382 --> n371
    n382 --> n372
    n382 --> n373
    n382 --> n374
    n382 --> n375
    n382 --> n376
    n382 --> n377
    n382 --> n378
    n382 --> n379
    n382 --> n380
    n382 --> n381
    n382 --> n186
    n382 --> n189
    n382 --> n190
    n382 --> n192
    n382 --> n193
    n382 --> n194
    n382 --> n195
    n382 --> n200
    n382 --> n201
    n382 --> n202
    n382 --> n203
    n382 --> n207
    n382 --> n208
    n382 --> n209
    n382 --> n210
    n382 --> n213
    n382 --> n215
    n382 --> n217
    n382 --> n221
    n382 --> n223
    n382 --> n225
    n382 --> n227
    n382 --> n229
    n382 --> n232
    n382 --> n233
    n382 --> n234
    n382 --> n237
    n382 --> n238
    n382 --> n239
    n382 --> n240
    n382 --> n241
    n382 --> n242
    n382 --> n243
    n382 --> n244
    n382 --> n248
    n382 --> n143
    n384 --> n143
    n384 --> n177
    n384 --> n224
    n385 --> n143
    n385 --> n191
    n385 --> n177
    n386 --> n143
    n386 --> n177
    n387 --> n143
    n387 --> n177
    n387 --> n196
    n387 --> n156
    n388 --> n143
    n388 --> n177
    n388 --> n197
    n388 --> n141
    n389 --> n143
    n389 --> n172
    n389 --> n140
    n390 --> n143
    n391 --> n143
    n391 --> n172
    n391 --> n140
    n392 --> n143
    n392 --> n177
    n392 --> n131
    n393 --> n183
    n393 --> n143
    n393 --> n177
    n394 --> n154
    n394 --> n143
    n394 --> n177
    n395 --> n154
    n395 --> n143
    n395 --> n177
    n395 --> n141
    n396 --> n183
    n396 --> n143
    n396 --> n177
    n397 --> n143
    n397 --> n172
    n397 --> n140
    n398 --> n131
    n398 --> n143
    n398 --> n177
    n398 --> n156
    n402 --> n431
    n406 --> n407
    n414 --> n405
    n418 --> n424
    n418 --> n412
    n420 --> n404
    n425 --> n326
    n426 --> n430
    n433 --> n30
    n433 --> n404
    n440 --> n175
    n441 --> n175
    n444 --> n351
    n447 --> n0
    n448 --> n449
    n451 --> n448
    n451 --> n452
    n452 --> n449
    n452 --> n450
