/**
 * Bug category: Type Errors / Null Safety (separate file)
 *
 * None-dereference, Optional narrowing, union-attr cluster.
 * Caught primarily by mypy (type system) + hypothesis (property test).
 * R7 IMPROVED NullSafetyScanner to catch dict.get().attr chain.
 */

import type { BugDetail } from "./bugs-critical"

export const TYPE_ERROR_BUGS: BugDetail[] = [
  {
    id: "R7-1a",
    title: "CryptoResult.value None-comparison (crypto path)",
    file: "scp/runtime/slms_parts/conversionslm.py",
    line: 322,
    severity: "CRITICAL",
    bugType: "TypeError (None > 0)",
    rootCause:
      "CryptoResult.value: float | None. When crypto sources fail → value=None → `value > 0` raises TypeError → except swallows → SILENT fail.",
    beforeCode: `if result.value > 0:  # TypeError when value=None`,
    afterCode: `if result.value is not None and result.value > 0:`,
    realityTest: [
      "T1 CryptoResult(value=None) → False ✓",
      "T2 CryptoResult(value=50000) → True ✓",
      "T3 hypothesis 1000 random inputs → 0 TypeError ✓",
    ],
    sources: ["mypy", "hypothesis", "scp-scanners"],
    tier: 2,
    isR5R6Incomplete: true,
  },
  {
    id: "R7-1b",
    title: "CryptoResult.value None-comparison (currency path, R6-1 missed)",
    file: "scp/runtime/slms_parts/conversionslm.py",
    line: 355,
    severity: "CRITICAL",
    bugType: "TypeError (None > 0) — R6-1 incomplete",
    rootCause:
      "Same CryptoResult pattern in currency conversion. R6-1 only fixed crypto path (line 322), missed currency path (line 355). R7-1b fixes both.",
    beforeCode: `if result.value > 0:  # currency path, R6-1 missed`,
    afterCode: `if result.value is not None and result.value > 0:`,
    realityTest: ["T1 currency path None guard ✓", "T2 hypothesis currency inputs → 0 TypeError ✓"],
    sources: ["mypy", "hypothesis"],
    tier: 2,
    isR5R6Incomplete: true,
  },
  {
    id: "R7-1c",
    title: "currency rate dict None-comparison (misc_slm.py)",
    file: "scp/runtime/slm_impls/misc_slm.py",
    line: 118,
    severity: "CRITICAL",
    bugType: "TypeError (dict value None > 0)",
    rootCause:
      "fetch_currency_rate returns {value: None, ...} on failure. misc_slm checks `if rate['value'] > 0` → KeyError or TypeError when None. R6-1 used `rate.get('value', 0)` which masks None (returns 0, then 0 > 0 is False, silently degrades). R7-1c uses explicit None check.",
    beforeCode: `if rate.get('value', 0) > 0:  # None masked as 0, silent degrade`,
    afterCode: `value = rate.get('value')
if value is not None and value > 0:`,
    realityTest: ["T1 None explicit ✓", "T2 hypothesis rate dicts → 0 TypeError ✓"],
    sources: ["mypy", "hypothesis"],
    tier: 2,
    isR5R6Incomplete: true,
  },
  {
    id: "R7-1d",
    title: "numeric_data_slm None-comparison",
    file: "scp/runtime/slm_impls/numeric_data_slm.py",
    line: 87,
    severity: "CRITICAL",
    bugType: "TypeError (None > 0)",
    rootCause: "Same CryptoResult pattern, numeric_data path.",
    beforeCode: `if result.value > 0:`,
    afterCode: `if result.value is not None and result.value > 0:`,
    realityTest: ["T1 None guard ✓"],
    sources: ["mypy", "hypothesis"],
    tier: 2,
    isR5R6Incomplete: true,
  },
  {
    id: "R7-1e",
    title: "misc_slms2 currency None-comparison",
    file: "scp/runtime/slms_parts/misc_slms2.py",
    line: 156,
    severity: "CRITICAL",
    bugType: "TypeError (None > 0)",
    rootCause: "Same pattern, misc_slms2 currency.",
    beforeCode: `if rate.get('value', 0) > 0:`,
    afterCode: `value = rate.get('value')
if value is not None and value > 0:`,
    realityTest: ["T1 None guard ✓"],
    sources: ["mypy", "hypothesis"],
    tier: 2,
    isR5R6Incomplete: true,
  },
  {
    id: "R7-1f",
    title: "chem_reality_astro_slm None-comparison (chemistry)",
    file: "scp/runtime/slm_impls/chem_reality_astro_slm.py",
    line: 203,
    severity: "CRITICAL",
    bugType: "TypeError (None > 0)",
    rootCause: "Same pattern, chemistry conversion path.",
    beforeCode: `if result.value > 0:`,
    afterCode: `if result.value is not None and result.value > 0:`,
    realityTest: ["T1 None guard ✓"],
    sources: ["mypy", "hypothesis"],
    tier: 2,
    isR5R6Incomplete: true,
  },
  {
    id: "R7-1g",
    title: "conversionslm None-comparison (currency fallback)",
    file: "scp/runtime/slms_parts/conversionslm.py",
    line: 388,
    severity: "CRITICAL",
    bugType: "TypeError (None > 0) — fallback path",
    rootCause: "Currency fallback path also has None-comparison.",
    beforeCode: `if result.value > 0:`,
    afterCode: `if result.value is not None and result.value > 0:`,
    realityTest: ["T1 None guard ✓"],
    sources: ["mypy", "hypothesis"],
    tier: 2,
    isR5R6Incomplete: true,
  },
  {
    id: "R7-1h",
    title: "misc_slm crypto None-comparison (second site)",
    file: "scp/runtime/slm_impls/misc_slm.py",
    line: 142,
    severity: "CRITICAL",
    bugType: "TypeError (None > 0) — second crypto site",
    rootCause: "Second crypto None-comparison site in misc_slm.",
    beforeCode: `if result.value > 0:`,
    afterCode: `if result.value is not None and result.value > 0:`,
    realityTest: ["T1 None guard ✓"],
    sources: ["mypy", "hypothesis"],
    tier: 2,
    isR5R6Incomplete: true,
  },
  {
    id: "R7-15",
    title: "dict.get('key').attr chain — NullSafetyScanner R7 improvement",
    file: "scp/knowledge/source_reputation.py",
    line: 412,
    severity: "MEDIUM",
    bugType: "AttributeError (dict.get returns None)",
    rootCause:
      "config.get('timeout').seconds — dict.get returns None if key missing → None.seconds raises AttributeError. R6 NullSafetyScanner missed this (only checked function returns, not dict.get chain). R7 IMPROVED scanner catches it.",
    beforeCode: `timeout = config.get('timeout').seconds  # AttributeError if 'timeout' missing`,
    afterCode: `timeout_cfg = config.get('timeout')
timeout = timeout_cfg.seconds if timeout_cfg else 30  # safe default`,
    realityTest: [
      "T1 dict.get('missing') → None → safe default 30 ✓",
      "T2 dict.get('present') → use .seconds ✓",
      "T3 NullSafetyScanner R7 catches this pattern (was missed in R6) ✓",
    ],
    sources: ["scp-scanners", "mypy"],
    tier: 2,
    isR5R6Incomplete: false,
  },
]
