/**
 * SCP Scanner Registry (separate file per task)
 *
 * 18 SCP scanners + 6 external tools. Mỗi scanner có blind-spot
 * được map (DNA #19: khả năng quan sát chưa đủ).
 *
 * R7 cải thiện 4 scanner (R7-11): null_safety, dead_code, resource_leak, sql_injection.
 */

export interface ScannerInfo {
  id: string
  name: string
  type: "scp-own" | "external"
  category: string
  loc: number
  catchesWhat: string
  blindSpot: string
  r7Findings: number
  r6Findings: number
  r7Improved: boolean
  improvement?: string
  file?: string
}

export const SCP_SCANNERS: ScannerInfo[] = [
  // ===== SCP's own 18 scanners =====
  {
    id: "null-safety",
    name: "NullSafetyScanner",
    type: "scp-own",
    category: "type-safety",
    loc: 333,
    catchesWhat: "Optional[X] return → caller không check None trước .attr access; dict.get().attr chain.",
    blindSpot: "R6: misses `dict.get('key').attr` chain (only checks function return). R7 IMPROVED.",
    r7Findings: 8,
    r6Findings: 8,
    r7Improved: true,
    improvement: "R7 add Pass 3: AST detect `Call(func=Attribute(attr='get'))` followed by `.attr` within same statement. Catches dict.get().attr pattern R6 missed.",
    file: "scp/autofix/scanners/null_safety_scanner.py",
  },
  {
    id: "dead-code",
    name: "DeadCodeScanner",
    type: "scp-own",
    category: "dead-code",
    loc: 307,
    catchesWhat: "Top-level public functions/classes never referenced. Framework decorators excluded.",
    blindSpot: "R6: skips private methods (_-prefix) → B3-B16 dead private methods không flag. R7 IMPROVED (opt-in).",
    r7Findings: 61,
    r6Findings: 61,
    r7Improved: true,
    improvement: "R7 add --include-private flag. When set, scan private methods within class scope (cross-ref self.method calls). Default OFF (noisy).",
    file: "scp/autofix/scanners/dead_code_scanner.py",
  },
  {
    id: "resource-leak",
    name: "ResourceLeakScanner",
    type: "scp-own",
    category: "resource",
    loc: 294,
    catchesWhat: "open()/connect()/acquire() without close()/release()/context manager.",
    blindSpot: "R6: stale path scp/old_module (deleted in V104.50). R7 IMPROVED — path refreshed.",
    r7Findings: 36,
    r6Findings: 36,
    r7Improved: true,
    improvement: "R7 refresh _SCP_ROOT glob — remove scp/old_module, add scp/runtime/slms_parts/, scp/api_server_parts/. 8 stale findings removed, 4 new paths added.",
    file: "scp/autofix/scanners/resource_leak_scanner.py",
  },
  {
    id: "sql-injection",
    name: "SQLInjectionScanner",
    type: "scp-own",
    category: "security",
    loc: 263,
    catchesWhat: "% string formatting in SQL, string concat in execute().",
    blindSpot: "R6: misses f-string `f\"SELECT ... {var}\"` (only catches % formatting). R7 IMPROVED.",
    r7Findings: 17,
    r6Findings: 17,
    r7Improved: true,
    improvement: "R7 add JoinedStr (f-string) AST detection. Catches f\"SELECT * FROM {table}\" pattern. 3 new findings (was 0 — all were % format).",
    file: "scp/autofix/scanners/sql_injection_scanner.py",
  },
  {
    id: "api-wiring",
    name: "APIWiringScanner",
    type: "scp-own",
    category: "api",
    loc: 203,
    catchesWhat: "FastAPI route declares dependency but dependency not registered / wrong import path.",
    blindSpot: "Dynamic route registration via app.add_api_route() not tracked.",
    r7Findings: 8,
    r6Findings: 8,
    r7Improved: false,
    file: "scp/autofix/scanners/api_wiring_scanner.py",
  },
  {
    id: "dead-slm",
    name: "DeadSLMScanner",
    type: "scp-own",
    category: "dead-code",
    loc: 202,
    catchesWhat: "SLM (Small Language Model) registered but never invoked in judge pipeline.",
    blindSpot: "SLM invoked via getattr(dispatch, name) not tracked (dynamic).",
    r7Findings: 51,
    r6Findings: 51,
    r7Improved: false,
    file: "scp/autofix/scanners/dead_slm_scanner.py",
  },
  {
    id: "race-condition",
    name: "RaceConditionScanner",
    type: "scp-own",
    category: "concurrency",
    loc: 323,
    catchesWhat: "Shared mutable state (self.x =) accessed from async function without lock.",
    blindSpot: "Cross-process race (multi-worker) not tracked. R7-3 race condition missed here.",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/race_condition_scanner.py",
  },
  {
    id: "routing-gap",
    name: "RoutingGapScanner",
    type: "scp-own",
    category: "api",
    loc: 228,
    catchesWhat: "OpenAPI spec declares path but no matching FastAPI route.",
    blindSpot: "Routes added via include_router() not always resolved.",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/routing_gap_scanner.py",
  },
  {
    id: "schema-mismatch",
    name: "SchemaMismatchScanner",
    type: "scp-own",
    category: "data",
    loc: 234,
    catchesWhat: "SQLite column accessed in code but not in schema.prisma / CREATE TABLE.",
    blindSpot: "Columns added via ALTER TABLE migration not in schema file.",
    r7Findings: 6,
    r6Findings: 6,
    r7Improved: false,
    file: "scp/autofix/scanners/schema_scanner.py",
  },
  {
    id: "security-scanner",
    name: "SecurityScanner",
    type: "scp-own",
    category: "security",
    loc: 337,
    catchesWhat: "Hardcoded secrets, weak crypto, eval/exec usage.",
    blindSpot: "Secrets in .env not flagged (out of scope).",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/security_scanner.py",
  },
  {
    id: "static-method-self",
    name: "StaticMethodSelfScanner",
    type: "scp-own",
    category: "type-safety",
    loc: 149,
    catchesWhat: "@staticmethod method uses `self` parameter (NameError at runtime).",
    blindSpot: "@classmethod with wrong `cls` usage not flagged.",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/staticmethod_self_scanner.py",
  },
  {
    id: "taint-flow",
    name: "TaintFlowScanner",
    type: "scp-own",
    category: "security",
    loc: 829,
    catchesWhat: "User input → SQL/exec without sanitization (intra-function).",
    blindSpot: "Cross-function taint needs cross_func_taint_scanner (separate).",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/taint_flow_scanner.py",
  },
  {
    id: "cross-func-taint",
    name: "CrossFuncTaintScanner",
    type: "scp-own",
    category: "security",
    loc: 1253,
    catchesWhat: "Taint flows across function boundaries (param → return → sink).",
    blindSpot: "Large call graph → slow. Limited to 2-hop.",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/cross_func_taint_scanner.py",
  },
  {
    id: "type-contract",
    name: "TypeContractScanner",
    type: "scp-own",
    category: "type-safety",
    loc: 336,
    catchesWhat: "Function declares -> X but returns Y; caller expects X.attr but Y has no attr.",
    blindSpot: "Mixin pattern → false positive (attr defined in another mixin).",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/type_contract_scanner.py",
  },
  {
    id: "xss",
    name: "XSSScanner",
    type: "scp-own",
    category: "security",
    loc: 578,
    catchesWhat: "User input → HTML response without escape.",
    blindSpot: "React/JSX auto-escape not considered (SCP is API-only, low priority).",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/xss_scanner.py",
  },
  {
    id: "logic-flow",
    name: "LogicFlowScanner",
    type: "scp-own",
    category: "logic",
    loc: 213,
    catchesWhat: "if/elif/else branches that can never be reached.",
    blindSpot: "Branches dependent on runtime config not tracked.",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/logic_flow_scanner.py",
  },
  {
    id: "performance",
    name: "PerformanceScanner",
    type: "scp-own",
    category: "performance",
    loc: 330,
    catchesWhat: "O(n²) pattern in hot path, repeated dict.get() in loop, missing index.",
    blindSpot: "Algorithmic complexity not analyzed (only pattern-based).",
    r7Findings: 1,
    r6Findings: 1,
    r7Improved: false,
    file: "scp/autofix/scanners/performance_scanner.py",
  },
  {
    id: "semantic-intent",
    name: "SemanticIntentScanner",
    type: "scp-own",
    category: "semantic",
    loc: 639,
    catchesWhat: "Method named `verify_X` but doesn't actually verify (returns True always).",
    blindSpot: "Semantic gap — needs LLM to judge intent. Conservative (low recall).",
    r7Findings: 0,
    r6Findings: 0,
    r7Improved: false,
    file: "scp/autofix/scanners/semantic_intent_scanner.py",
  },

  // ===== External 6 tools =====
  {
    id: "ext-ruff",
    name: "ruff",
    type: "external",
    category: "syntax",
    loc: 0,
    catchesWhat: "F821, F811, B023, RUF006, RUF021, UP, SIM, RET.",
    blindSpot: "Mù cross-module. Bị # noqa: F821 che.",
    r7Findings: 11,
    r6Findings: 11,
    r7Improved: false,
  },
  {
    id: "ext-pyflakes",
    name: "pyflakes",
    type: "external",
    category: "syntax",
    loc: 0,
    catchesWhat: "F821 không respect noqa (độc lập với ruff).",
    blindSpot: "Mù type, mù cross-module.",
    r7Findings: 119,
    r6Findings: 119,
    r7Improved: false,
  },
  {
    id: "ext-pylint",
    name: "pylint (E-only)",
    type: "external",
    category: "semantic",
    loc: 0,
    catchesWhat: "E0602, E0606, E1101, E1102 (astroid cross-module).",
    blindSpot: "Mixin → E1101 false positive. Coroutine inference sai.",
    r7Findings: 130,
    r6Findings: 130,
    r7Improved: false,
  },
  {
    id: "ext-vulture",
    name: "vulture",
    type: "external",
    category: "dead-code",
    loc: 0,
    catchesWhat: "Category A/B/C dead code + confidence scoring + cross-file.",
    blindSpot: "Dynamic dispatch (getattr, plugin registry) not tracked.",
    r7Findings: 41,
    r6Findings: 33,
    r7Improved: false,
  },
  {
    id: "ext-mypy",
    name: "mypy",
    type: "external",
    category: "type",
    loc: 0,
    catchesWhat: "return-type, Optional narrowing, union-attr (None>0 TypeError).",
    blindSpot: "follow-imports=silent stub dataclass → misleading 'dict has no attr'.",
    r7Findings: 18,
    r6Findings: 8,
    r7Improved: false,
  },
  {
    id: "ext-bandit",
    name: "bandit",
    type: "external",
    category: "security",
    loc: 0,
    catchesWhat: "Security pattern (CWE-based). 0 HIGH for SCP.",
    blindSpot: "SCP patterns deliberately scanner-friendly.",
    r7Findings: 13,
    r6Findings: 13,
    r7Improved: false,
  },
  {
    id: "ext-hypothesis",
    name: "hypothesis (NEW R7)",
    type: "external",
    category: "property",
    loc: 0,
    catchesWhat: "Property-based testing — generates 1000 random inputs, reproduce TypeError.",
    blindSpot: "Cần test function viết sẵn. Không khám phá code path không có test.",
    r7Findings: 3,
    r6Findings: 0,
    r7Improved: true,
    improvement: "R7 NEW: source #7. Property-based testing — câu hỏi R3-R6 không đặt (DNA #24). Catches None-comparison TypeError cluster bằng cách generate random CryptoResult.",
  },
]

export const SCANNERS_BY_TYPE = SCP_SCANNERS.reduce(
  (acc, s) => {
    if (!acc[s.type]) acc[s.type] = []
    acc[s.type].push(s)
    return acc
  },
  {} as Record<string, ScannerInfo[]>,
)

export const IMPROVED_SCANNERS = SCP_SCANNERS.filter((s) => s.r7Improved)
