from mutation_engine import run_mutation_tests
import os
import sys
import json
import time
import subprocess
import ast
import queue
import threading
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from scp.llm_gateway.client import chat_sync

# Queue to prevent race conditions in watcher
autofix_queue = queue.Queue()

def get_missing_lines(target_file_rel: str) -> list[int]:
    """Run coverage for a specific file and return missing line numbers."""
    mod_name = target_file_rel.replace("/", ".").replace("\\", ".")
    if mod_name.endswith(".py"):
        mod_name = mod_name[:-3]
    
    subprocess.run(
        ["pytest", f"--cov={mod_name}", "--cov-report=json", "tests/"],
        cwd=str(ROOT), capture_output=True
    )
    
    cov_file = ROOT / "coverage.json"
    if not cov_file.exists():
        print(f"[TestFactory] ERROR: coverage.json not generated.")
        return []
        
    try:
        data = json.loads(cov_file.read_text())
        files = data.get("files", {})
        for fpath, fdata in files.items():
            if target_file_rel.replace("\\", "/") in fpath.replace("\\", "/"):
                return fdata.get("missing_lines", [])
    except json.JSONDecodeError as e:
        print(f"[TestFactory] ERROR: Failed to parse coverage.json - {e}")
    except Exception as e:
        print(f"[TestFactory] ERROR: Unexpected error reading coverage - {e}")
    
    return []

def run_test_file(test_file: Path) -> tuple[bool, str]:
    """Run pytest on a specific file and return (success, output)."""
    res = subprocess.run(["pytest", str(test_file)], cwd=str(ROOT), capture_output=True, text=True)
    return res.returncode == 0, res.stdout + "\n" + res.stderr

def validate_ast(code: str) -> bool:
    try:
        ast.parse(code)
        return True
    except SyntaxError as e:
        print(f"[TestFactory] AST Validation Failed: {e}")
        return False

def autofix_test_generation(target_file_rel: str, force_mutation: bool = True):
    """The SCP Autofix loop for generating and fixing tests (Safe Version)."""
    missing = get_missing_lines(target_file_rel)
    if not missing:
        print(f"[TestFactory] {target_file_rel} has no missing coverage lines. Skipping.")
        return

    target_path = ROOT / target_file_rel
    if not target_path.exists():
        return

    code_content = target_path.read_text(encoding="utf-8")
    
    parts = Path(target_file_rel).parts
    if parts[0] == "scp":
        parts = parts[1:]
    test_file_name = "test_" + "_".join(parts)
    test_path = ROOT / "tests" / test_file_name
    draft_path = ROOT / "tests" / (test_file_name + ".draft")
    
    existing_test = ""
    if test_path.exists():
        existing_test = test_path.read_text(encoding="utf-8")

    print(f"[TestFactory] Generating coverage for {target_file_rel} (missing {len(missing)} lines)")
    
    system_prompt = (
        "You are the SCP Test Factory Autofix Engine. DO NOT optimize for mere line coverage. You MUST shift the primary metrics to mutation score, contract invariants, regression reproducers, and property/differential tests (e.g. using hypothesis). Output ONLY valid Python code block. Do not write explanations."
    )
    
    context = f"Target File: {target_file_rel}\n\nCode:\n```python\n{code_content}\n```\nMissing Coverage Lines: {missing}\n"
    if existing_test:
        context += f"Existing Test File ({test_file_name}):\n```python\n{existing_test}\n```\nModify this to cover missing lines."
    else:
        context += f"Create a new test file {test_file_name}."

    question = "Write the complete updated test file python code."
    
    for attempt in range(3):
        print(f"[TestFactory] Autofix attempt {attempt + 1}/3...")
        response, _ = chat_sync(question, context=context, system_prompt=system_prompt, task="test_factory")
        
        if not response:
            print("[TestFactory] LLM failed to respond.")
            return
            
        code_block = response
        if "```python" in response:
            code_block = response.split("```python")[1].split("```")[0].strip()
        elif "```" in response:
            code_block = response.split("```")[1].split("```")[0].strip()
            
        if not validate_ast(code_block):
            context = "The generated code has SyntaxErrors (AST parsing failed). Please fix it."
            continue
            
        header = "# WARNING: Generated by Autofix. High line coverage does NOT guarantee contract correctness or mutation survival.\n"
        draft_path.write_text(header + code_block, encoding="utf-8")
        
        success, output = run_test_file(draft_path)
        if success:
            print(f"[TestFactory] SUCCESS! Tests passed. Saving to {test_path.name}")
            if test_path.exists():
                backup = test_path.with_suffix(".py.bak")
                test_path.replace(backup)
            draft_path.replace(test_path)
            break
        else:
            print(f"[TestFactory] Test failed. Feeding error back...")
            context = f"The test failed with this output:\n```\n{output}\n```\nPlease fix the test code."

def worker_loop():
    while True:
        target = autofix_queue.get()
        if target is None:
            break
        try:
            autofix_test_generation(target)
        except Exception as e:
            print(f"[TestFactory] Worker error on {target}: {e}")
        finally:
            autofix_queue.task_done()

def watch_loop():
    try:
        from watchdog.observers import Observer
        from watchdog.events import FileSystemEventHandler
    except ImportError:
        print("[TestFactory] ERROR: watchdog package is required. Run 'pip install watchdog' first.")
        sys.exit(1)

    class CodeWatcher(FileSystemEventHandler):
        def on_modified(self, event):
            if event.is_directory or not event.src_path.endswith(".py"):
                return
            rel_path = Path(event.src_path).relative_to(ROOT).as_posix()
            if not rel_path.startswith("scp/") or rel_path.startswith("scp/tests/"):
                return
            
            print(f"\n[Watcher] Detected update in {rel_path}. Queuing Test Factory...")
            autofix_queue.put(rel_path)

    worker = threading.Thread(target=worker_loop, daemon=True)
    worker.start()

    observer = Observer()
    observer.schedule(CodeWatcher(), path=str(ROOT / "scp"), recursive=True)
    observer.start()
    print("[TestFactory] Watchdog daemon activated. Listening for core tech updates...")
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
    autofix_queue.put(None)
    worker.join()

if __name__ == "__main__":
    if "--watch" in sys.argv:
        watch_loop()
    elif len(sys.argv) > 1 and sys.argv[1].endswith(".py"):
        autofix_test_generation(sys.argv[1])
    else:
        print("Usage: python scp_test_factory.py [--watch | path/to/target.py]")